### ISSUE TITLE
Country name is miss in some Language.

### ISSUE THREAD

**Issue by lychees** [crypto-meetup-dev/cryptomeetup-portal#135]

**Comment by shellteo** [comment]
https://github.com/crypto-meetup-dev/cryptomeetup-portal/pull/180
这个代码里面已经改掉了

**Comment by lychees** [comment]
It seems that zh-tw is still missing!
Hope someone can solve this problem in future.
https://github.com/michaelwittig/node-i18n-iso-countries/pull/121

**Comment by lychees** [comment]
Let's use English when there is no language support by default!

**Comment by lychees** [comment]
zh-tw is still missing! Have you ever test it?
@shellteo
