### ISSUE TITLE
需要设置用户查看地标的权限

### ISSUE THREAD

**Issue by guanchao71** [crypto-meetup-dev/cryptomeetup-portal#163]
用户在没有登录的时候，只可以查看到别人上传的处于“已拥有”“未开放”状态地标。
用户在登录之后，可以查看到自己和别人上传的处于“已拥有”和“未开放”状态地标。同时增加可以查看到自己上传的处于“审核中”状态的地标。
用户不可以查看到别人上传的处于“审核中”的地标。
[文档](https://github.com/crypto-meetup-dev/crypto-meetup-docment/blob/master/requirements_documentation/%E5%9C%B0%E6%A0%87%E6%89%93%E5%8D%A1%E5%8A%9F%E8%83%BD.md)

**Comment by webkonglong** [comment]
【用户在没有登录的时候，只可以查看到别人上传的处于“已拥有”“未开放”状态地标  】
 未登录无法判断 地标是否是用户的。 如果 按照 上面描述去做，那就需要在未登录 请求一次 所有地标，然后登录以后，把在未登录请求的地标丢弃 从新请求一次？确定要这样做吗？
