### ISSUE TITLE
当用户 CMU 余额为 0 时，Token 显示为空。

### ISSUE THREAD

**Issue by lychees** [crypto-meetup-dev/cryptomeetup-portal#176]
<img width="494" alt="2018-11-27 10 40 42" src="https://user-images.githubusercontent.com/2507027/49090958-cc853480-f299-11e8-83d2-fb344adcba4b.png">

**Comment by LittleSound** [comment]
![image](https://github.com/LittleSound/gallery/blob/master/Tu/123.png)

**Comment by webkonglong** [comment]
已修复
