### ISSUE TITLE
Unstake 时不会自动补全到  4 位。

### ISSUE THREAD

**Issue by lychees** [crypto-meetup-dev/cryptomeetup-portal#197]
stake 的时候会。

**Comment by webkonglong** [comment]
@lychees 是Unstake提交给合约的时候未自动补全到小数点后4 这个问题吧，这个已修复。
如果是别的 地方，请具体描述。

**Comment by lychees** [comment]
https://github.com/crypto-meetup-dev/cryptomeetup-portal/pull/198
