### ISSUE TITLE
User Page.

### ISSUE THREAD

**Issue by lychees** [crypto-meetup-dev/cryptomeetup-portal#2]
请参考 https://betdice.one 的 红利 设计 Token 页面。
【红利池（Payout Pool）】【我的资产（My Assets）】
【抵押（Stake）】【Bancor 交易（Bancor Trade）】

四个 Tab。

## 显示数据：
 - [x] 显示 EOS 余额
 - [x] 显示 CMU  余额
 - [x] 显示 我的抵押
 - [ ] 我持有的地产（参考加密名人的实现——）

## 按钮
- [x] 购买 buy
- [x] 卖出 sell
- [x] 抵押 stake
- [ ] 取消抵押 unstake
- [x] 领取分红 claim

## 其他
- [ ] k 线图

抵押的查询方法：
cleos -u http://api-direct.eosasia.one get table cryptomeetup minakokojima voters
{
  "rows": [{
      "to": "",
      "staked": 10000
    }
  ],
  "more": false
}

抵押的方法：
cleos -u http://api-direct.eosasia.one push action dacincubator transfer '[ "minakokojima", "cryptomeetup", "1.0000 CMU", "stake" ]' -p minakokojima@active

**Comment by lucky917** [comment]
查询发行量、储备金与币价
现在需要显示 流通量，储备金 和 合约币价*

cleos -u http://api.eosbeijing.one get table cryptomeetup cryptomeetup market

发行量：supply，初始 40000000.0000 CMU
储备金：balance，初始 80000.0000 EOS
币价：supply/10000000000 ，初始 0.004 EOS/CMU

**Comment by lychees** [comment]
Almost done.
