### ISSUE TITLE
支持价格排序来选择国家，下拉菜单支持搜索，自动匹配

### ISSUE THREAD

**Issue by seaify** [crypto-meetup-dev/cryptomeetup-portal#28]

**Comment by lychees** [comment]
Please refer to the following implementation:
- https://armsglobe.chromeexperiments.com/ 
- https://github.com/dataarts/armsglobe

Another known bug, you cannot use the search box unless you click one country in the map.

**Comment by seaify** [comment]
原来的下拉菜单，换成select2插件不就好了么.

**Comment by crazycoder1988** [comment]
Actually there is already an autocomplete in buefy: https://buefy.github.io/documentation/autocomplete

**Comment by lychees** [comment]
This feature has been deprecated.
