### ISSUE TITLE
bug|mac pro老款电脑前端不展示地图

### ISSUE THREAD

**Issue by busayyou** [crypto-meetup-dev/cryptomeetup-portal#33]
![image](https://user-images.githubusercontent.com/44598132/47698618-ff142100-dc4a-11e8-8840-0016be5f4183.png)

**Comment by lychees** [comment]
May I know the version of your web browser?

**Comment by busayyou** [comment]
![image](https://user-images.githubusercontent.com/44598132/47836924-066f3200-dde5-11e8-9d26-84e18b34cec3.png)
![image](https://user-images.githubusercontent.com/44598132/47836935-125af400-dde5-11e8-9524-0c6201dc989d.png)

Google Chrome 已是最新版本
版本 70.0.3538.77（正式版本） （64 位）

mac版本：10.11.6 (15G22010）

**Comment by busayyou** [comment]
> May I know the version of your web browser?

**Comment by crypt0sh0j0** [comment]
我的推测：应该是你的电脑的显卡不支持地球的渲染（使用了高级的浏览器canvas渲染技术，对显卡有一定要求）
这种情况，建议升级系统并升级显卡驱动，或使用近两年的手机，通过EOS的钱包App打开
