### ISSUE TITLE
Help page or FaQ page, please

### ISSUE THREAD

**Issue by SakuraKaori** [crypto-meetup-dev/cryptomeetup-portal#42]
Develop the help page, お願いします。The medium logo is too small, and there's nothing helpful in it. We want a page to describe the rules clearly and is in the right front of our face. Make it a good product, boys.

**Comment by aDappDeveloper** [comment]
> Develop the help page, お願いします。The medium logo is too small, and there's nothing helpful in it. We want a page to describe the rules clearly and is in the right front of our face. Make it a good product, boys.

We added about page on the website. Thanks!
