### ISSUE TITLE
Counter Down 移动端适配

### ISSUE THREAD

**Issue by lychees** [crypto-meetup-dev/cryptomeetup-portal#49]
Last updated: Today at 9:49 AM
Count Down: ENDED

看起来 Last updated 这个信息没有什么信息量？
需要把这个位置换成 LAST BUYER?

**Comment by crypt0sh0j0** [comment]
Replaced in #50, but i am not sure how to display these 2 items in mobile

**Comment by crypt0sh0j0** [comment]
For mobile Ended in #51
